name: TMA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Create .env file
      run: |
        echo "MONGO_URI=mongodb+srv://dhaker:Machete12@cluster0.sfwvvqe.mongodb.net/pfe?retryWrites=true&w=majority" >> .env
        echo "PORT=3000" >> .env
        echo "EMAIL=karousdhaker@gmail.com" >> .env
        echo "PASSWORD=gwweapbhbxohctih" >> .env
        echo "MONGO_TEST_URI=mongodb+srv://dhaker:Machete12@cluster0.sfwvvqe.mongodb.net/pfe_test?retryWrites=true&w=majority" >> .env
        echo "TEST_PASSWORD=test123" >> .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test



