name: TMA-back-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: 'Create env file'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env 
        cat .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    #- run: npm test
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/test:latest
        
    - name: Create kubeconfig
      run: |
        sudo mkdir $HOME/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > $HOME/.kube/config
        sudo cat $HOME/.kube/config
    - name: Use context
      run: kubectl config use-context kubernetes-admin@kubernetes
      
    - name: Deploy to Kubernetes
      run: kubectl apply -f test.yml
